version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/sites-available:/etc/nginx/sites-available
      - ${PWD}:/var/www/html
      - /etc/nginx/sites-available/default:/etc/nginx/sites-enabled/default
    command: /bin/bash -c "ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/ && nginx -g 'daemon off;'"

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ${PWD}:/var/www/html

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
